# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy app to Github Pages

on:
  push:
    branches: [ "main" ]
jobs:
  build_and_deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: bitovi/github-actions-react-to-ghp@v1.2.0
